version: "3"
services:
  api:
    restart: always
    build: .
    container_name: "api"
    working_dir: "/root/"
    volumes:
      - ./opt:/root/opt
      - ./app:/root/app
    # command: mkdir -p /root/opt/sample
    tty: true
    expose:
      - "8000"
    ports:
      - 8000:8000
